import React from 'react'
import { Typography } from '@material-ui/core'

export default function MenuList() {
  return (
    <div className="menu">
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
      <Typography>Pizzas</Typography>
    </div>
  )
}
